name: CI/CD to MonsterASP.NET
on:
  push:
    branches:
      - master  # Adjust if you use a different branch for deployment

jobs:
  build_and_deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0
          
      - name: Install Dependencies
        run: dotnet restore
        
      - name: Run Tests
        run: dotnet test --configuration Release

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish --runtime win-x64 --self-contained false 
        
      - name: Deploy to MonsterASP.NET via WebDeploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.WEBSITE_NAME }}  # Set in GitHub Secrets
          publish-profile: ${{ secrets.PUBLISH_SETTINGS }}  # Set in GitHub Secrets as a base64 string
          package: ./publish
